# ===== 第一阶段：编译 Go 程序 =====
FROM golang:1.24 AS builder

# 容器内工作目录
WORKDIR /app

# 先复制依赖文件
COPY go.mod go.sum ./

# 下载依赖
RUN go mod download

# 复制源码 COPY  <来源路径>  <目标路径>
COPY . .

# 编译静态二进制
RUN CGO_ENABLED=0 GOOS=linux go build -o app .

# ===== 第二阶段：极简运行环境 =====
FROM alpine:latest

WORKDIR /root/

# 从 builder 阶段复制二进制
COPY --from=builder /app/app .

# 复制静态文件目录
COPY --from=builder /app/static ./static

# 暴露端口
EXPOSE 8080

# 启动程序
CMD ["./app"]